### ISSUE TITLE
Save Dolphin Configuration

### ISSUE THREAD

**Issue by ChrTall** [Prayag2/konsave#42]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to save the setttings for dolphin in your config.
I adjust the toolbar for dolphin and its layout for different Themes.

**Describe the solution you'd like**
Dolphin Configuration gets also saved.

Thanks for your effort, it is a nice tool.
The Plasma Config Saver Plasmoid was always buggy and slow for me. I am glad I found this alternative.

**Comment by Prayag2** [comment]
To do that, you can add the following below the line saying `save:` in `~/.config/konsave/conf.yaml`:
```
dolphin:
    location: "$HOME/.local/share/kxmlgui5/dolphin/"
    entries:
        - dolphinui.rc
```

You can add as many config files as you want :)
